import { useEffect, useState } from "react";
import Header from "@components/Header";
import Head from "next/head";
import styles from "@styles/Home.module.css";
import TaskInput from "@components/TaskInput";
import TodoList from "@components/TodoList";
import Filters from "@components/Filters";
import { useSelector, useDispatch } from "react-redux";
import { getTodosAsync } from "@redux/todoSlice";
import Nav from "@components/Nav";

export default function Home() {
  const [selectedFilter, setSelectedFilter] = useState("all");

  const dispatch = useDispatch();
  const todos = useSelector((state) => {
    switch (selectedFilter) {
      case "all":
        return state.todos;
      case "completed":
        return state.todos.filter((todo) => todo.completed === true);
      case "incompleted":
        return state.todos.filter((todo) => todo.completed === false);
      default:
        return state.todos;
    }
  });

  useEffect(() => {
    dispatch(getTodosAsync());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Simpledo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className={styles.main}>
        <div className={styles.todoContainer}>
          <Header title="Todo List" />
          <TaskInput placeholder="Add a new todo" />
          <TodoList todos={todos} />
          <Filters
            setSelectedFilter={setSelectedFilter}
            selectedFilter={selectedFilter}
          />
        </div>
      </main>
    </div>
  );
}
